env:
  - CGO_ENABLED=0
before:
  hooks:
    - go mod download
    - go test -v -cover ./pkg/... ./flex/cmd/...
builds:
  - main: ./flex/main.go
    binary: flex
    goos:
      - linux
      - darwin
    goarch:
      - amd64
    ldflags:
      - -s -w -X devx-workflows/pkg/version.FlexVersion={{ .Version }}
archives:
  -
    name_template: "flex_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}{{ if .Mips }}_{{ .Mips }}{{ end }}"
    files:
      - scripts/user/*
release:
  github:
    owner: fp-mt    
    name: flex
  extra_files:
    - glob: ./scripts/user/flex.sh
changelog:
  sort: asc
