flex:
  version: 0.1.3
  workflows:
    build:
      command: auto_install=1 auto_clean=0 ./scripts/build-flex.sh
    test:
      command: ./scripts/test-flex.sh
    build-test:
      depends-on:
      - build
      - test
service:
  name: flex
